name: xmake

on:
  push:
    branches: [ main ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: minsizerel

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: Configure
      run: xmake f -y -m ${{ env.BUILD_TYPE }}

    - name: Build
      run: xmake b -y 

    - name: Pack
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: xmake p -y 

    - name: Release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.workspace }}/build/package/*.7z
    
#   - name: Test
#     working-directory: ${{ github.workspace }}/build
#     run: ctest -C ${{ env.BUILD_TYPE }}
      
